### ISSUE TITLE
Feature: function that tells if inside flatpak

### ISSUE THREAD

**Issue by sophie-h** [bilelmoussaoui/ashpd#10]
As we have seen with the background portal, there are cases where it is required to know if an app is run inside a flatpak or not. Maybe this would fit for ashpd?

xdg-open uses the existence of `$XDG_RUNTIME_DIR/flatpak-info` as indicator. I also spotted

```
FLATPAK_ID=...
container=flatpak
```

which might be better because they can be overwritten?

**Comment by bilelmoussaoui** [comment]
We can check if /.flatpak exists
