### ISSUE TITLE
Screencast request fails with Other

### ISSUE THREAD

**Issue by MalekiRe** [bilelmoussaoui/ashpd#100]
![image](https://user-images.githubusercontent.com/50841145/208227788-7e79b7b7-d667-4a2a-bebe-8a4f0eac0b9a.png)
This is just running the demo, same thing happens if I try to actually write/use code, the error is throne at the
```
let session = proxy.create_session();
```
for when trying to do this in code. `Error: Portal request didn't succeed: Other`

**Comment by bilelmoussaoui** [comment]
Something must be happening from the portal itself, not ashpd.

**Comment by bilelmoussaoui** [comment]
Closing as this is probably an issue on the xdg-desktop-portal implementation you are using
