### ISSUE TITLE
Blocking API

### ISSUE THREAD

**Issue by jneem** [bilelmoussaoui/ashpd#11]
If I want to wait for a result (using the non-async API), it looks something like:

```rust
    let connection = Connection::new_session()?;
    let proxy = FileChooserProxy::new(&connection);
    let req = proxy.open_file(Default::default(), "Title", Default::default())?;

    req.connect_response(|r: Response<SelectedFiles>| {
        // Do something
        Ok(())
    })?;
    while reply.next_signal()?.is_some() {}
```

Would you consider adding (or accepting a PR to add) an API that just blocks until a response is ready? Like:
```rust
    let connection = Connection::new_session()?;
    let proxy = FileChooserProxy::new(&connection);
    let selected: SelectedFiles = proxy.open_file(Default::default(), "Title", Default::default())?;
```

Or maybe something in between, which would still allow for cancellation:
```rust
    let connection = Connection::new_session()?;
    let proxy = FileChooserProxy::new(&connection);
    let req = proxy.open_file(Default::default(), "Title", Default::default())?;
    let selected: SelectedFiles = req.response()?;
```

It would be even cooler if the type of `req` encoded the fact that the response has to be of type `SelectedFiles`. Although from what I can tell, doing this would involve some changes to the `dbus_proxy` macro...

**Comment by bilelmoussaoui** [comment]
I was thinking of completely removing the non-async API for the next release

**Comment by jneem** [comment]
Ok, fair enough. I just re-wrote using the async API, and it seems to share the same patterns. AFAICT, I need to write

```rust
    let connection = Connection::new_session().await?;
    let proxy = AsyncFileChooserProxy::new(&connection);
    let reply = proxy
        .open_file(Default::default(), "Title", Default::default())
        .await?;

    reply
        .connect_response(|r: Response<SelectedFiles>| {
            // Do something...
            Box::pin(futures::future::ok(()))
        })
        .await?;

    while reply.next_signal().await?.is_some() {}
```

But I'd like to just write

```rust
    let connection = Connection::new_session().await?;
    let proxy = FileChooserProxy::new(&connection).await?;
    let selected: SelectedFiles = proxy.open_file(Default::default(), "Title", Default::default()).await?;
```

**Comment by bilelmoussaoui** [comment]
> Ok, fair enough. I just re-wrote using the async API, and it seems to share the same patterns. AFAICT, I need to write
> 
> ```rust
>     let connection = Connection::new_session().await?;
>     let proxy = AsyncFileChooserProxy::new(&connection);
>     let reply = proxy
>         .open_file(Default::default(), "Title", Default::default())
>         .await?;
> 
>     reply
>         .connect_response(|r: Response<SelectedFiles>| {
>             // Do something...
>             Box::pin(futures::future::ok(()))
>         })
>         .await?;
> 
>     while reply.next_signal().await?.is_some() {}
> ```
> 
> But I'd like to just write
> 
> ```rust
>     let connection = Connection::new_session().await?;
>     let proxy = FileChooserProxy::new(&connection).await?;
>     let selected: SelectedFiles = proxy.open_file(Default::default(), "Title", Default::default()).await?;
> ```

That part is ugly mostly because of the missing https://gitlab.freedesktop.org/dbus/zbus/-/issues/142, once that part is done the code could be written as simply as 
```
>     let connection = Connection::new_session().await?;
>     let proxy = FileChooserProxy::new(&connection).await?;
>     let req = proxy.open_file(Default::default(), "Title", Default::default()).await?;
>    let files = req.response::<SelectedFiles>()?.await;
```
(very pseudo code) 

Of course, that's still ugly with the whole Response thing. I was thinking of keeping Request as is so that I can keep using `dbus_proxy` macro on it. But I suppose ideally, we will have to implement manually and have a generic Error that could either contain a `zbus::Error` or a `ashpd::ResponseError`. Having to drop the extra call to `req.response::<SelectedFiles>().await` would be a bit complicated as we will have to manually implement all the proxies...

**Comment by bilelmoussaoui** [comment]
Note that I added some simple function wrappers for some of the proxies such as `ashpd::desktop::screenshot::pick_color`
```rust
pub async fn pick_color(window_identifier: WindowIdentifier) -> zbus::Result<Response<Color>> {
    let connection = zbus::azync::Connection::new_session().await?;
    let proxy = AsyncScreenshotProxy::new(&connection);
    let request = proxy
        .pick_color(window_identifier, PickColorOptions::default())
        .await?;

    let (sender, receiver) = futures::channel::oneshot::channel();

    let sender = Arc::new(Mutex::new(Some(sender)));
    let signal_id = request
        .connect_response(move |response: Response<Color>| {
            let s = sender.clone();
            async move {
                if let Some(m) = s.lock().await.take() {
                    let _ = m.send(response);
                }
                Ok(())
            }
            .boxed()
        })
        .await?;

    while request.next_signal().await?.is_some() {}
    request.disconnect_signal(signal_id).await?;

    let color = receiver.await.unwrap();
    Ok(color)
}
```
with such helper function on top of the AsyncProxy, you can just write
```rust
use ashpd::{desktop::screenshot, Response, WindowIdentifier};
use zbus::fdo::Result;

async fn run() -> Result<()> {
    let identifier = WindowIdentifier::default();
    if let Response::Ok(screenshot) = screenshot::take(identifier, true, false).await? {
        println!("URI: {}", screenshot.uri);
    }
    Ok(())
}
```

Of course that's still that nice due to the `Response::Ok(_)` but still much better :)  I'm open to providing more helpers for other portals if that would simplify things on your side?  I didn't get around doing that for the file chooser one as I didn't got to implement a demo for it as part of the `ashpd-demo`.

**Comment by jneem** [comment]
> That part is ugly mostly because of the missing https://gitlab.freedesktop.org/dbus/zbus/-/issues/142

Oh, very cool! That will already be a big improvement.

> Note that I added some simple function wrappers for some of the proxies such as `ashpd::desktop::screenshot::pick_color`

This sounds like a place where macros might help? I'd be happy to take a stab at writing one if it's something you'd consider adding.

**Comment by bilelmoussaoui** [comment]
> > That part is ugly mostly because of the missing https://gitlab.freedesktop.org/dbus/zbus/-/issues/142
> 
> Oh, very cool! That will already be a big improvement.
> 
> > Note that I added some simple function wrappers for some of the proxies such as `ashpd::desktop::screenshot::pick_color`
> 
> This sounds like a place where macros might help? I'd be happy to take a stab at writing one if it's something you'd consider adding.
> 
> 

Feel free to work on that, I have been busy working on gtk4 bindings so far, I will probably not get back to it anytime soon

**Comment by bilelmoussaoui** [comment]
I opened a PR that make use of the new SignalStream API. I also made all the Proxies manually implemented instead of using the dbus_proxy macro. 

The API is much nicer to use now. Feel free to give it a try if you want

**Comment by bilelmoussaoui** [comment]
This issue can be closed, you can now write
```rust
    let connection = zbus::azync::Connection::new_session().await?;
    let proxy = FileChooserProxy::new(&connection).await?;
    let files = proxy.open_file(Default::default(), "Title", Default::default()).await?;
```

**Comment by jneem** [comment]
I haven't had a chance to give it a try yet, but that looks awesome. Thanks!
