### ISSUE TITLE
Seems the upstream of pipewire is broken.. with the new pipewire

### ISSUE THREAD

**Issue by Decodetalkers** [bilelmoussaoui/ashpd#118]
![image](https://user-images.githubusercontent.com/60290287/217703360-abec01da-f0b3-4acb-8c4b-a16cf44ccfda.png)

**Comment by bilelmoussaoui** [comment]
There is an issue open on pipwire side already, nothing I can do about it

**Comment by A6GibKm** [comment]
One could add 
```
[patch.crates-io]
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs", branch = "main" }
```
to cargo, but I don't know if this is desirable.

**Comment by bilelmoussaoui** [comment]
the latest alpha should build just fine

**Comment by Decodetalkers** [comment]
> the latest alpha should build just fine

Thanks, fixed
