### ISSUE TITLE
Open things on the correct `$DISPLAY`.

### ISSUE THREAD

**Issue by jneem** [bilelmoussaoui/ashpd#12]
This may be an upstream issue, but here it is anyway: if I'm running multiple X servers on different ttys, there's a chance that the file dialog I request pops up on the wrong X server. I'm running arch linux, and it uses per-user (as opposed to per-session) dbus daemons.

Steps to reproduce:
1. Clone the repo [here](https://github.com/jneem/file-chooser-test)
2. Run two X servers on different ttys.
3. Go to one of the ttys, cd to your git clone, run `cargo run`. If the file dialog shows up, switch to the other tty and repeat. At least one of them will show the file dialog on the other tty.

**Comment by bilelmoussaoui** [comment]
Do you have a parent window that would be in different tty or none at all?

**Comment by jneem** [comment]
In this linked example, I have no parent window. But I have other very-much-not-minimal examples (in particular, the `open_save` example in [this PR](https://github.com/linebender/druid/pull/1774), which isn't currently using `ashpd` but I have a local branch where it is) where I am setting a parent window and still see the bad cross-tty behavior. But maybe I'm setting the parent window wrong? I was following the documentation [here](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#parent_window), but IIUC XIDs are not unique across different instances of the X server, and I don't see any way to specify the DISPLAY.

**Comment by bilelmoussaoui** [comment]
That's probably an issue on the xdg-desktop-portals/whatever compositor you're running side. ashpd doesn't do much other doing the dbus calls while providing a nice rust wrappers around the various things. 

I don't know much about x11 so I can't really help here

**Comment by bilelmoussaoui** [comment]
Also, super cool to see that PR. Please let me know if there's something I can provide in the next release to help you with that/simplify things for you on that regards :)

**Comment by jneem** [comment]
Thanks! I've opened an issue with xdg-desktop-portals.

I think the main things I was wanting from `ashpd` is #11 (which I'm still planning to look into eventually), plus maybe some indication that the API is settled-ish. It's always hard to know about that when the version number is so low :)

**Comment by bilelmoussaoui** [comment]
> I think the main things I was wanting from ashpd is #11 (which I'm still planning to look into eventually), plus maybe some indication that the API is settled-ish. It's always hard to know about that when the version number is so low :)

I'm planning to do more cleanup once zbus 2.0 is out, drop the sync variant of the portals and finish up the demo application which should be a good enough test case for ensuring the various portals are working as expected. 

Once that's done, I'm going to do a new "major" release and mark it as stable enough for wider use cases.
