### ISSUE TITLE
`Documents::add_full` errors with `InvalidAppID` if `app_id` is empty string

### ISSUE THREAD

**Issue by ids1024** [bilelmoussaoui/ashpd#129]
This function is supposed to take an app ID **or** an empty string, but `TryFrom<String>` calls `is_valid_app_id`, which returns `false` for empty strings.

This should also apply to `add_named_full` and `list`.

Would it be better to skip using a `TryFrom` generic here, and accept `Option<AppId>`? That would probably be more idiomatic, and let the caller deal with (fallible) conversion.

**Comment by bilelmoussaoui** [comment]
> Would it be better to skip using a TryFrom generic here, and accept Option<AppId>?

Mind submitting a patch?
