### ISSUE TITLE
Receive color scheme changed does not work

### ISSUE THREAD

**Issue by d2weber** [bilelmoussaoui/ashpd#148]
The function
https://github.com/bilelmoussaoui/ashpd/blob/471bae1fb9376ae92f572e0c91c428149ec89190/src/desktop/settings.rs#L161
does not seem to work. The following program never returns.

```toml
# Cargo.toml
[dependencies]
ashpd = "0.4.0"
```

```rust
// src/main.rs
use ashpd::{desktop::settings, zbus::block_on};

fn main() {
    block_on(async {
        let settings = settings::Settings::new().await.unwrap();
        let s = settings.receive_color_scheme_changed().await.unwrap();
        dbg!(s);
    });
}
```

I'm using Ubuntu 22.04.2 LTS (GNOME 42.9)

The loop in `receive_color_scheme_changed` waits for a changed setting, checks if it matches it's filters and if it doeesn't, checks again for a changed setting. I suspect that there are settings that are not matching the filter criteria and while the checks are being made, the _desired_ setting changed message arrives. But they are gone by the time that the loop will check for changed settings again.

I also don't quite understand the concept of hiding away the `Stream` interface of the signals, see https://github.com/bilelmoussaoui/ashpd/blob/471bae1fb9376ae92f572e0c91c428149ec89190/src/proxy.rs#L157 Why isn't the stream returned directly? The user can then call `next().await` and discard the stream to achieve the current behaviour of `receive_setting_changed` and `receive_color_scheme_changed`. I also tried to find any uses of this interface in the demo folder and the rest of github but I couldn't find any.

I believe it would be useful for the user to get the stream, I have an implementation [here](https://github.com/d2weber/tintanum/blob/main/src/lib.rs#L86-L94) and I would submit a PR to integrate it in ashpd if it is desired.

**Comment by bilelmoussaoui** [comment]
> I believe it would be useful for the user to get the stream, I have an implementation [here](https://github.com/d2weber/tintanum/blob/main/src/lib.rs#L86-L94) and I would submit a PR to integrate it in ashpd if it is desired.

Patches would be welcome, only if all the other signals are replaced with returning an actual stream
