### ISSUE TITLE
Is ashpd-demo/Cargo.lock supposed to be in git?

### ISSUE THREAD

**Issue by whot** [bilelmoussaoui/ashpd#149]
excuse this potential noob question but - is this supposed to be in git? seems like for fixed deployments it may be tracked in git but for general development it'll get generated by the various dependencencies anyway?

**Comment by bilelmoussaoui** [comment]
Yes, all the binary applications must ship their .lock file for builds reproducibility

**Comment by whot** [comment]
ah, right, that makes sense, thanks!
