### ISSUE TITLE
Add InputCapture support

### ISSUE THREAD

**Issue by orowith2os** [bilelmoussaoui/ashpd#156]
Should be fairly simple, it's just passing a file descriptor around with some setup beforehand.

**Comment by bilelmoussaoui** [comment]
Not sure wdym here? For the demo?

**Comment by orowith2os** [comment]
I didn't see it in the bindings themselves at a quick glance, but yes, support in the demo would be nice too - but first the reis crate needs to be less low-level.

**Comment by bilelmoussaoui** [comment]
Ah I see, well as always, PRs are welcome :)

**Comment by whot** [comment]
> but first the reis crate needs to be less low-level.

fwiw, the portal bits don't actually do anything with libei, you can make this take an fd and that's it (that's what the xdg-desktop-portal and libportal tests doo as well, pass a socket fd, write "vanilla" and check on the other end that you can read that)

**Comment by bilelmoussaoui** [comment]
For the demo, I rather track that separately as it is not a requirement.

**Comment by bilelmoussaoui** [comment]
Basic impl have landed
