### ISSUE TITLE
Sometimes get `Invalid client serial`

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/ashpd#16]
It is very hard to reproduce as it happens very rarely. Although, it is reproducible from the demo through screencast by creating a session. (Haven't tested other)

The log shows the following:
`** (process:43167): WARNING **: 14:41:02.960: Invalid client serial`

The process 43167, according to system monitor, is `xdg-dbus-proxy`.

I'll add some additional information, ill try to debug

**Comment by bilelmoussaoui** [comment]
That looks like an issue on the portal side probably

**Comment by SeaDve** [comment]
could it be the randomizer from window identifier?

**Comment by bilelmoussaoui** [comment]
> could it be the randomizer from session handle?

No I don't think so, the handle is correctly validated per dbus types définitions

**Comment by SeaDve** [comment]
after a long time, i was able to reproduce it again. The CreateSession calls succeeded, then the warning occurs. I think it may not had received the response from SelectSources

**Comment by bilelmoussaoui** [comment]
That doesn't help, as I can't reproduce it here. Maybe the portal crashed ? Nothing obvious on the logs ? From the other sides as well. E.g, xdg-desktop-portal/xdg-desktop-portal-gtk?

**Comment by SeaDve** [comment]
I'll try to get more info when I am able to reproduce it again

**Comment by SeaDve** [comment]
was able to reproduce again, I checked on journalctl logs of the xdg-desktop-portal and xdg-desktop-portal-gtk. I didn't see anything relevant. (I'm not sure though if im looking at the right place)

**Comment by bilelmoussaoui** [comment]
I will go ahead and close this, I don't see anything that could cause this from ashpd side

**Comment by A6GibKm** [comment]
The actual issue is https://github.com/flatpak/xdg-dbus-proxy/issues/46.
