### ISSUE TITLE
Links to the DBus interfaces no longer point to the right place

### ISSUE THREAD

**Issue by carlosmn** [bilelmoussaoui/ashpd#168]
If you open one of the doc pages, e.g. https://docs.rs/ashpd/0.6.7/ashpd/desktop/email/index.html it has a link to the relevant DBus interface on the portals site, in that case https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-org.freedesktop.portal.Email

But currently that just takes you to the main landing page instead of the relevant interface. Presumably this is because of the recent update to the portals' website and the right URL now is https://flatpak.github.io/xdg-desktop-portal/docs/#gdbus-org.freedesktop.portal.Email so maybe the actual docs didn't change the format it's easy and it's a simple addition of `/docs/` to the link.

**Comment by bilelmoussaoui** [comment]
Yes, I just fixed it https://github.com/bilelmoussaoui/ashpd/commit/840c60d145acdc69b6ad1024d87aecf9b50cc0c4

**Comment by bilelmoussaoui** [comment]
What a timing though :)

**Comment by bilelmoussaoui** [comment]
Should be fixed in both main & latest stable
