### ISSUE TITLE
unable to build `ashpd-demo` on Ubuntu 23.10

### ISSUE THREAD

**Issue by kgilmer** [bilelmoussaoui/ashpd#174]
I saw `ashpd-demo` during a portals demo by the GNOME desktop team at Ubuntu Summit last week, and was hoping to try it out myself.  I am able to compile the root project without problem, however when compiling `ashpd-demo` I see the following compilation error:

```
$ cargo build
   Compiling ashpd-demo v0.3.0 (/home/kgilmer/dev/repos/ashpd/ashpd-demo)
error[E0583]: file not found for module `config`
 --> src/main.rs:3:1
  |
3 | mod config;
  | ^^^^^^^^^^^
  |
  = help: to create the module `config`, create file "src/config.rs" or "src/config/mod.rs"
```

My rust toolchain info:

```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kgilmer/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.66.1-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

I tried `HEAD` and the most recent tag (`0.6.3`) but the behavior is the same.  Any suggestions on how to move forward?

**Comment by bilelmoussaoui** [comment]
You should build it using meson not cargo. or use the flatpak from flathub.
