### ISSUE TITLE
input_capture portal Signals are not working

### ISSUE THREAD

**Issue by feschber** [bilelmoussaoui/ashpd#187]
The `receive_activate()` / `receive_deactivate()` Streams on the `input_capture` portal never yield any Result.

I did some digging and could narrow it down a bit:

`receive_activated` calls `signal("Activated")` which yields a Stream that filter-maps on the result of `msg.body::<Activated>().ok()`

So I tried to replicated the `body()` call manually and it always throws the following error:
```
called `Result::unwrap()` on an `Err` value: Variant(Message("invalid type: character `o`, expected `v`, `a` or `(`"))
```
Which then of course results in the signal getting filtered by the filter_map call.

This error in `body` is originated from `zvariant::from_slice_fds_for_dynamic_signature` -> `deserializer_for_signature` -> ... -> `deserialize_seq` where it ultimately fails in `zbus/zvariant/src/dbus/de.rs:347` because it does not expect an `o`.

**Comment by bilelmoussaoui** [comment]
I think the signature is wrong; so I would replicate the code outside of ashpd, use `msg.body::<zvariant::Value>()` an then call `dbg!(value.value_signature())` and share the output?

**Comment by feschber** [comment]
Thank you so much! I wanted to get back to this this week but I guess I don't have to!

When I checked the flatpak docs, I totally missed the missing () ...

**Comment by bilelmoussaoui** [comment]
No worries! the error message could have been better from zbus... Anyways, i will be doing a release shortly that includes this

**Comment by feschber** [comment]
Im now running into this issue:
```Msg { type: Signal, sender: UniqueName(":1.55"), path: ObjectPath("/org/freedesktop/portal/desktop"), iface: InterfaceName("org.freedesktop.portal.InputCapture"), member: MemberName("Activated"), body: Signature("oa{sv}"), fds: [] }
thread 'main' panicked at /home/ferdinand/git/lan-mouse/src/backend/producer/libei.rs:122:30:
failed to deserialize body: Variant(PaddingNot0(1))
```

Do you have an example where you got this to work correctly?

**Comment by bilelmoussaoui** [comment]
That looks like a completely different issue. You would have to debug it yourself as I am not familiar with libei and don't have the time to dig into it now

**Comment by feschber** [comment]
sorry I was a bit unclear but it's still kind of the same problem and I still can not receive the Activated signal because of it.
The signature now seems to get built correctly but parsing fails with this error message.
I will look into it and see what I can find.

**Comment by whot** [comment]
>  The signature now seems to get built correctly but parsing fails with this error message.

which error message? The `Variant(PaddingNot0)`? It's a bit hard to guess without seeing the code you use to parse ([this source](https://github.com/feschber/lan-mouse/blob/main/src/backend/producer/libei.rs) doesn't have a line 120).

Probably worth checking with dbus-monitor to see what's being sent and comparing this to your parsing code.

**Comment by feschber** [comment]
one second

**Comment by feschber** [comment]
https://github.com/feschber/ashpd-mre

this is basically what I've tried so far.

**Comment by feschber** [comment]
In lan-mouse the [libei-producer](https://github.com/feschber/lan-mouse/tree/libei-producer) branch contains my attempts. (but with more irrelevant stuff)

**Comment by whot** [comment]
I have no idea tbh, this looks like it's inside the dictionary deserialization but I don't know how this one works. From a quick look at [input_capture.rs](https://github.com/bilelmoussaoui/ashpd/blob/master/src/desktop/input_capture.rs) that bit looks correct, I don't know if you can somehow hook extra debug messages into the deserialization code to figure out what it's trying to do.

**Comment by feschber** [comment]
found the culprit!
