### ISSUE TITLE
Add persistence and session restore for the RemoteDesktop portal.

### ISSUE THREAD

**Issue by Adamskye** [bilelmoussaoui/ashpd#200]
Like with the ScreenCast portal, the RemoteDesktop portal allows for specifying persist mode and may return some restore data so that a program wouldn't need to prompt the user every time they want to use it. This should probably be implemented the same way that it has been for the ScreenCast portal.

**Comment by Adamskye** [comment]
There is already a struct for PersistMode in screencast.rs, and I wasn't sure whether I should have reused this one or created a new one for remote desktop. I opted for the latter option, if that's okay.

**Comment by bilelmoussaoui** [comment]
This is now handled but let us keep the issue open till we add it to the demo as well

**Comment by bilelmoussaoui** [comment]
Fixed in https://github.com/bilelmoussaoui/ashpd/commit/47aa993a24c20c568ab535f7f95cb597494dcf46
