### ISSUE TITLE
Unable to get WindowIdentifier on wayland due to protocol error when using gtk-layer-shell

### ISSUE THREAD

**Issue by oddlama** [bilelmoussaoui/ashpd#213]
Hi! I'm trying to wrap my head around how to use the GlobalShortcuts portal, and hit an issue while trying to get a `WindowIdentifier` to register the session. The main issue seems to be that I am using `gtk-layer-shell` to create a dock-style window that is overlayed on top of everything else. I would have liked to use portals to be able to register shortcuts to the otherwise unfocusable wnidow, but as soon as the layer shell is initialized, any call to `WindowIdentifier::get_native` will return a protocol error:

```
Gdk-Message: 16:23:36.485: Error 71 (Protocol error) dispatching to Wayland display.
```

This can easily be reproduces by adding `gtk-layer-shell` and running `window.init_layer_shell();`. Any subsequent call to `WindowIdentifier::from_native` will now fail. It does not matter which method is used, manually calling `WindowIdentifier::from_wayland` also fails.

I'm not a wayland expert, so now I am unsure whether what I am trying to do is generally unsupported by the wayland protocol, or whether this is an issue with ashpd. 

<details>
<summary>My cargo dependencies</summary>

```
ashpd = { version = "0.9.0", git = "https://github.com/bilelmoussaoui/ashpd.git", features = ["gtk4_wayland", "wayland"] }
gdk = { version = "0.8.2", package = "gdk4", features = ["v4_14"] }
gdk-wayland = { version = "0.8.2", package = "gdk4-wayland", features = ["wayland_crate", "v4_12"] }
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }
gtk-layer-shell = { version = "0.3.0", package = "gtk4-layer-shell" }
```

</details>

**Comment by bilelmoussaoui** [comment]
i don't think it is related to ashpd itself as it just uses a [wayland protocol
(https://wayland.app/protocols/xdg-foreign-unstable-v2) either directly by calling `from_wayland` or indirectly through gtk with `from_native`.

If both fails with the error you shared above, it is very probably some limitation in the wayland protocol. 

From a quick look it seems you could only export a toplevel surface, so maybe the layer-shell surface is not a toplevel one?

**Comment by oddlama** [comment]
> If both fails with the error you shared above, it is very probably some limitation in the wayland protocol.

That's too bad. Both of them fail, although with a slightly different error reporting. But the underlying issue seems to be the same.

> From a quick look it seems you could only export a toplevel surface, so maybe the layer-shell surface is not a toplevel one?

Yeah that might be the case. But then I don't believe there's any way around that. Thanks for your time.

**Comment by bilelmoussaoui** [comment]
If you end up figuring out what is happening, please keep me updated
