### ISSUE TITLE
ashpd-demo failed to start a screen cast session 

### ISSUE THREAD

**Issue by crab2313** [bilelmoussaoui/ashpd#22]
Env: the lastest archlinux with GNOME 

This is the error message.

```
Sep 14 21:26:59.638 ERROR ashpd_demo::portals::desktop::screencast: Portal(
    ZBus(
        FDO(
            NameHasNoOwner(
                "Could not get owner of name 'org.freedesktop.portal.Desktop': no such name",
            ),
        ),
    ),
)
```

It seems that the org.freedesktop.portal.Desktop service is not start automatically. ashpd-demo works fine after I launch the service manually.

**Comment by bilelmoussaoui** [comment]
The issue is on how you configured your system. It's not related to the ashpd library at all.

**Comment by crab2313** [comment]
I don't think its related to my configuration. obs-studio on wayland works fine on my system. It will launch the org.freedesktop.portal.Desktop service before using it for screen capture.

**Comment by crab2313** [comment]
@bilelmoussaoui I have checked that the service is activatable in d-feet.  And calling dbus-send with following command will launch the service:

```bash
dbus-send --session --print-reply --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Notification.RemoveNotification string:xxxx
```

I'm not sure whether this is an issue of zbus.

**Comment by crab2313** [comment]
@bilelmoussaoui After research the issue, I find that it is caused by zbus and affects ashpd as well. Since ashpd uses zbus 2.0.0-beta6. The upstream of zbus has fix this issue already by this [MR]( https://gitlab.freedesktop.org/dbus/zbus/-/merge_requests/367). I think we should keep this issue open until zbus publish a new beta. Since this issue makes ashpd broken when the org.freedesktop.portal.Desktop dbus service is not activated.

**Comment by bilelmoussaoui** [comment]
The issue will fix itself once we update to the next zbus beta. Which should happen before we release a 0.2 beta here. I don't see a point of keeping the issue open here if it's already fixed upstream
