### ISSUE TITLE
Windows and GTK4?

### ISSUE THREAD

**Issue by OSA413** [bilelmoussaoui/ashpd#225]
I'm currently trying to build the [first todo example](https://github.com/gtk-rs/gtk4-rs/tree/master/book/listings/todo/1) from the [gtk4-rs book](https://gtk-rs.org/gtk4-rs/stable/latest/book/todo_1.html) and it looks like the project requires this library as dependency during build. It fails because it tries to build `gtk4-wayland` and sometimes `gtk4-x11`. Is this intended behavior?

Also you can comment out this library as dependency and the todo_1 starts to work, but other todo listings are failing with the following error:
```
(todo_2.exe:4552): GLib-GIO-ERROR **: 22:08:29.193: Settings schema 'org.gtk_rs.Todo2' is not installed
```

OS: Windows 11

Pre-requirements: prepared build environment as described in section ["Build GTK 4 with gvsbuild and MSVC (recommended)" on this page](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html).

Steps to reproduce:

```
git clone https://github.com/gtk-rs/gtk4-rs
cd ./gtk4-rs/book/listings 
cargo run --bin todo_1
```

**Comment by bilelmoussaoui** [comment]
The example in the book is targetting linux, ashpd is a linux only library. If you are using windows, you should just remove the parts that uses ashpd and replace them with something else.

Feel free to report an issue against gtk4-rs to make the book conditionally use that on linux only.
