### ISSUE TITLE
`--filesystem=xdg-run/pipewire-0` reduces security

### ISSUE THREAD

**Issue by msizanoen1** [bilelmoussaoui/ashpd#23]
https://github.com/bilelmoussaoui/ashpd/blob/e082795083a86c78df5196c15759e34d742fcd8d/src/desktop/camera.rs#L121-L122
The portal doesn't return a node ID, but you can use the file descriptor returned by the portal to iterate the camera node IDs, making exposing `xdg-run/pipewire-0` unneccesary. The portal sets up security restrictions on the socket before returning the socket to the application, but always ensures that the application can iterate and access camera devices.
`--filesystem=xdg-run/pipewire-0` is insecure as it allows the application to effectively bypass the permission prompt.

**Comment by bilelmoussaoui** [comment]
My pipewire knowledge is limited, feel free to contribute a patch to make the pipewire_node_id uses the fd returned by the portal directly. I didn't manage to do so

**Comment by msizanoen1** [comment]
This would require an API incompatible change as the application needs to pass the file descriptor to the function.

**Comment by bilelmoussaoui** [comment]
That's not a problem as the V2 is not API stable yet. It's still an alpha so such change in the api is not problematic

**Comment by msizanoen1** [comment]
https://github.com/bilelmoussaoui/ashpd/blob/e082795083a86c78df5196c15759e34d742fcd8d/src/desktop/camera.rs#L113-L115

**Comment by msizanoen1** [comment]
https://github.com/bilelmoussaoui/ashpd/blob/e082795083a86c78df5196c15759e34d742fcd8d/src/desktop/camera.rs#L113-L115
Not passing a node id won't confuse GStreamer as GStreamer can automatically iterate through nodes itself. However if the underlying node is disconnected, `pipewire-media-session` may incorrectly reconnect the client to a node that the client don't have access to.

**Comment by bilelmoussaoui** [comment]
> https://github.com/bilelmoussaoui/ashpd/blob/e082795083a86c78df5196c15759e34d742fcd8d/src/desktop/camera.rs#L113-L115
> Not passing a node id won't confuse GStreamer as GStreamer can automatically iterate through nodes itself. However if the underlying node is disconnected, `pipewire-media-session` may incorrectly reconnect the client to a node that the client don't have access to.

It does though, if you start a camera stream and then started a screen cast session, the screen cast stream is rendered in your end app instead of the camera one.

You can try it with the ashpd-demo by yourself and see. Note you will need to comment the code that checks for a node ID for the camera stream

**Comment by msizanoen1** [comment]
Hmm... I was able to reproduce it on `pipewire-media-session` but not on my patched copy of [Wireplumber](https://pipewire.pages.freedesktop.org/wireplumber/). This is probably because if you don't give GStreamer a node ID, it will rely on the media session controller to auto-connect it, which connects to the wrong one.
I will test it against an unpatch Wireplumber later.
