### ISSUE TITLE
'Directory' flag lost on x11 when prompting the user to select a directory

### ISSUE THREAD

**Issue by B-Lorentz** [bilelmoussaoui/ashpd#232]
Found when debugging this issue:
https://github.com/zed-industries/zed/issues/17096

```rust
use ashpd::desktop::file_chooser::OpenFileRequest;
use gpui::*;

fn main() {
    App::new().run(|cx: &mut AppContext| {
        cx.spawn(|acx| async move {
            let request = OpenFileRequest::default()
                .modal(true)
                .title("test")
                .multiple(false)
                .directory(true)
                .send()
                .await
                .unwrap()
                .response();
            println!("{:?}", request)
        })
        .detach();
    });
}
```
the above code, run with
[dependencies]
ashpd = "0.9.1"
gpui = { git = "https://github.com/zed-industries/zed.git", rev = "00eed768ce5cc72ac6af7e161e5324d77f28031f" }

on my
OS: Linux X11 ubuntu 20.04, 
version number:    11.0
X.Org version: 1.20.13

will open the system file selector, but it ignores the directory(true) flag, only allowing me to select files, not directories.

**Comment by B-Lorentz** [comment]
After digging around, it seems I've an old version of 'FileChooser':
![image](https://github.com/user-attachments/assets/9f09b4d5-68ba-47f1-be52-76598f2e3dfa)
According to this, 'directory' was added in version 3:
https://github.com/flatpak/xdg-desktop-portal/blob/436188fb6f92fabcd1baf96b0063379b3e2759cd/data/org.freedesktop.portal.FileChooser.xml#L66
So I guess I don't have a choice but update my system, and ashpd is fine

**Comment by bilelmoussaoui** [comment]
Thanks for the updates, unfortunately we don't have a way to report that an option has been used even if it is not supported by the portal implementation in the user's machine. It is not easy to solve but we will eventually get there
