### ISSUE TITLE
ScreenCast: Whole monitor is overexposed/too bright

### ISSUE THREAD

**Issue by BlauFx** [bilelmoussaoui/ashpd#233]
Selecting a region or even the whole workspace works just fine. However as you can see in the video, when capturing the whole monitor, the output is way too bright/overexposed. 

https://github.com/user-attachments/assets/109dcf9b-d331-415e-b77b-5868190f8e89

Version: 0.4.1
Installed as a flatpak through flathub.

**Comment by bilelmoussaoui** [comment]
Sounds like a compositor issue. We don't do anything to the stream other than passing it to gstreamer to render it using the pipewire gstreamer plugin.
