### ISSUE TITLE
rename crate?

### ISSUE THREAD

**Issue by Be-ing** [bilelmoussaoui/ashpd#39]
Thanks for this crate! We are using it in https://github.com/frewsxcv/rust-dark-light/pull/10 and I'll try using it for https://github.com/PolyMeilex/rfd/issues/36 as well. I am confused by the name though. It doesn't show up when [searching "xdg"](https://crates.io/search?q=xdg) on crates.io. Would you consider renaming this to `xdg-desktop-portal` or `xdg-portal`?

**Comment by bilelmoussaoui** [comment]
We could add keywords for xdg, but no the name is great!

**Comment by bilelmoussaoui** [comment]
> I'll try using it for PolyMeilex/rfd#36 as well. 

That would be great, let me know if there is something I should provide from the library side before we do a 0.2 release

**Comment by bilelmoussaoui** [comment]
Actually we have xdg and portal as keywords, https://github.com/bilelmoussaoui/ashpd/blob/master/Cargo.toml#L7 no idea why the crates.io doesn't look at them...

**Comment by Be-ing** [comment]
Adding keywords would help... I still find the name strange. When I first saw it, I presumed that this was written for some specific device and got confused. Looking it up, it seems to be a reference to a [device in Half-Life](https://half-life.fandom.com/wiki/Aperture_Science_Handheld_Portal_Device)?

**Comment by bilelmoussaoui** [comment]
Well the keywords help actually
![image](https://user-images.githubusercontent.com/7660997/149802614-07b6baee-0c85-4fca-b2cd-69758490c39b.png)

and yes, it is a half life reference

**Comment by Be-ing** [comment]
This does show up searching "xdg" on crates.io... but it's [3 pages back](https://crates.io/search?page=3&q=xdg). It's more prominent on [lib.rs](https://lib.rs/search?q=xdg) but I still think it would be easy to overlook because of the name.

**Comment by bilelmoussaoui** [comment]
Well, that is because there are a ton of xdg crates. renaming it to xdg-portal won't help neither because if you search for xdg, it won't show up at the top.

**Comment by Be-ing** [comment]
> Actually we have xdg and portal as keywords

Maybe add `dbus` as a keyword too?

**Comment by bilelmoussaoui** [comment]
We can't have more than 5 keywords per crates.io restrictions :/

**Comment by bilelmoussaoui** [comment]
I have replaced the "documents" keyword with "dbus", let us close this one as renaming the crate is a no-go for me
