### ISSUE TITLE
conversion from WindowIdentifier to raw_window_handle::RawWindowHandle

### ISSUE THREAD

**Issue by Be-ing** [bilelmoussaoui/ashpd#40]
[raw_window_handle](https://lib.rs/crates/raw-window-handle) is a cross platform library abstracting over window handles for various windowing systems, including Wayland and X11. For cross platform code using ashpd, for example [rfd](https://github.com/PolyMeilex/rfd/pull/41/files#r786441219), it would be helpful for ashpd to provide an API to convert its WindowIdentifier type to raw_window_handle's RawWindowHandle type. Alternatively, perhaps ashpd could switch to using RawWindowHandle in its own API.

**Comment by bilelmoussaoui** [comment]
Closed this in favour of the remaining part at https://github.com/bilelmoussaoui/ashpd/issues/44
