### ISSUE TITLE
Git repository is missing tags for releases 

### ISSUE THREAD

**Issue by Be-ing** [bilelmoussaoui/ashpd#43]
https://github.com/bilelmoussaoui/ashpd/tags only shows one tag for 0.0.1-alpha.

**Comment by bilelmoussaoui** [comment]
I should start doing tags for the library as well, that one was for the demo application I wrote to test that all the features are working as expected +/-.

**Comment by bilelmoussaoui** [comment]
I just did with the 0.2 release
