### ISSUE TITLE
Trash Portal fails inside a Flatpak

### ISSUE THREAD

**Issue by fries1234** [bilelmoussaoui/ashpd#47]
When I try to use `trash::trash_file()` inside a Flatpak, it fails.

Heres the error I get with my [small test program](https://github.com/fries1234/ashpd-test) when its running inside a Flatpak.

```
An error occured while trying to trash the test file: Portal request failed: org.freedesktop.portal.Error.Failed: no description
```

**Comment by bilelmoussaoui** [comment]
Should be fixed in 0.2.3 after a cargo update :) let me know how that goes

**Comment by A6GibKm** [comment]
@fries1234 Could you confirm if this is working now?

**Comment by A6GibKm** [comment]
Note that if the portal is backed by glib, it might fail if not using the latest release (I am not even sure if the fix is in master or in a stable release).

**Comment by fries1234** [comment]
I tried it again with ashpd 0.3.2 and it seems like it gives the same error.
```
2022-06-16T02:49:20.841798Z  INFO ashpd::helpers: Calling method org.freedesktop.portal.Trash:TrashFile
2022-06-16T02:49:20.843853Z ERROR ashpd_test: An error occured while trying to trash the test file: Portal request failed: org.freedesktop.portal.Error.Failed: no description
```

This is on a fresh fully up to date Arch Linux virtual machine with the `xdg-desktop-portal-1.14.4-1`, `xdg-desktop-portal-gnome-42.1-1`, `xdg-desktop-portal-gtk-1.14.0-1` packages installed.

**Comment by A6GibKm** [comment]
I think you need glib from git, can you test that?

**Comment by A6GibKm** [comment]
Just installing glib on the sandbox should be enough, see https://github.com/flathub/org.gnome.baobab/blob/master/org.gnome.baobab.json#L29.

**Comment by bilelmoussaoui** [comment]
Closing as ashpd is doing the right thing currently
