### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by ModProg** [bilelmoussaoui/ashpd#48]
Is there any way of running the example?

I got this error when trying to start screen sharing when I ran the flat pack example and I wanted to try to troubleshoot it.
```
2022-03-01T21:00:51.806977Z ERROR ashpd_demo::portals::desktop::screencast: Zbus(
    Variant(
        Message(
            "missing field `streams`",
        ),
    ),
)
```

**Comment by bilelmoussaoui** [comment]
I think that can only happen if https://github.com/bilelmoussaoui/ashpd/blob/master/src/desktop/screencast.rs#L193 which is the response https://github.com/bilelmoussaoui/ashpd/blob/master/src/desktop/screencast.rs#L406 doesn't contain a `streams` key. I would start with looking at the version of xdg-desktop-portal that installed on your system.

You could also, write minimal rust code that just does the screencast example without any GUI around it and see how that works for you.

**Comment by ModProg** [comment]
I tried to get some insight doing that, and was able to get the response body and tried to get a string out of that:
```rs
&String::from_utf8(message.body_as_bytes()?.to_owned()) = Ok(
    "\u{0}\u{0}\u{0}\u{0}[\u{0}\u{0}\u{0}\u{e}\u{0}\u{0}\u{0}session_handle\u{0}\u{1}s\u{0}\u{0}\u{0}>\u{0}\u{0}\u{0}/org/freedesktop/portal/desktop/session/1_112/ashpd_TwSl4fXigp\u{0}",
)
```

I'm using `xdg-desktop-portal-wlr` do you have any ideas I could try to get this to work? Generally screensharing works in e.g. Firefox or OBS.

**Comment by bilelmoussaoui** [comment]
I would appreciate if you could tell me what is the version of xdg-desktop-portal you are using

**Comment by ModProg** [comment]
xdg-desktop-portal-1.12.1-1  xdg-desktop-portal-wlr-0.5.0-1

**Comment by bilelmoussaoui** [comment]
> I though on wayland you had to use the screencast protal for screen recording or is the another way to do it? Because it seems like Applications like Firefox and OBS are able to record the screen with xdg-desktop-portal-wlr.

Right, that is something I forgot about.

The issue is the string you shared on https://github.com/bilelmoussaoui/ashpd/issues/48#issuecomment-1056433132 is not really what I would have expected, that is for the session creating not for starting it. Mind sharing the code used to retrieve the message with?

**Comment by ModProg** [comment]
Maybe I send the wrong string. 

I know added in `helpers.rs:53`:
```rs
            #[cfg(feature = "log")]
            tracing::debug!(
                "Message body: '{:?}'",
                String::from_utf8_lossy(message.body_as_bytes()?)
            );
```
And then used `ashpd` with:

```rs
use ashpd::{
    desktop::screencast::{CursorMode, PersistMode::Application, ScreenCastProxy, SourceType},
    WindowIdentifier,
};

#[tokio::main]
async fn main() -> ashpd::Result<()> {
    let connection = zbus::Connection::session().await?;
    let proxy = ScreenCastProxy::new(&connection).await?;
    let session = &proxy.create_session().await?;

    env_logger::builder().init();

    proxy
        .select_sources(
            session,
            CursorMode::Embedded.into(),
            SourceType::Monitor.into(),
            false,
            None,
            Application,
        )
        .await?;
    println!("Selected");

    proxy
        .start(session, &WindowIdentifier::Other("Hi".to_owned()))
        .await?;

    Ok(())
}
```

The entire output is:
```
[2022-03-02T09:45:01Z INFO  ashpd::helpers] Calling a request method 'org.freedesktop.portal.ScreenCast:SelectSources'
[2022-03-02T09:45:01Z DEBUG ashpd::helpers] The body is: (
        SessionProxy(
            "/org/freedesktop/portal/desktop/session/1_204/ashpd_bjLYdaDZzd",
        ),
        SelectSourcesOptions {
            handle_token: HandleToken(
                "ashpd_17ekTfkWMy",
            ),
            types: Some(
                BitFlags<SourceType> {
                    bits: 0b1,
                    flags: Monitor,
                },
            ),
            multiple: Some(
                false,
            ),
            cursor_mode: Some(
                BitFlags<CursorMode> {
                    bits: 0b10,
                    flags: Embedded,
                },
            ),
            restore_token: None,
            persist_mode: Some(
                Application,
            ),
        },
    )
[2022-03-02T09:45:01Z INFO  ashpd::desktop::request] Creating a org.freedesktop.portal.Request /org/freedesktop/portal/desktop/request/1_204/ashpd_17ekTfkWMy
[2022-03-02T09:45:01Z INFO  ashpd::helpers] Listening to signal 'Response' on 'org.freedesktop.portal.Request'
[2022-03-02T09:45:01Z DEBUG ashpd::helpers] Received request path /org/freedesktop/portal/desktop/request/1_204/ashpd_17ekTfkWMy
[2022-03-02T09:45:02Z INFO  ashpd::helpers] Received signal 'Response' on 'org.freedesktop.portal.Request'
[2022-03-02T09:45:02Z DEBUG ashpd::helpers] Message body: '"\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"'
[2022-03-02T09:45:02Z DEBUG ashpd::helpers] Received response Ok(
        BasicResponse,
    )
Selected
[2022-03-02T09:45:02Z INFO  ashpd::helpers] Calling a request method 'org.freedesktop.portal.ScreenCast:Start'
[2022-03-02T09:45:02Z DEBUG ashpd::helpers] The body is: (
        SessionProxy(
            "/org/freedesktop/portal/desktop/session/1_204/ashpd_bjLYdaDZzd",
        ),
        WindowIdentifier(
            "Hi",
        ),
        StartCastOptions {
            handle_token: HandleToken(
                "ashpd_yhJG5wl3k7",
            ),
        },
    )
[2022-03-02T09:45:02Z INFO  ashpd::desktop::request] Creating a org.freedesktop.portal.Request /org/freedesktop/portal/desktop/request/1_204/ashpd_yhJG5wl3k7
[2022-03-02T09:45:02Z INFO  ashpd::helpers] Listening to signal 'Response' on 'org.freedesktop.portal.Request'
[2022-03-02T09:45:02Z DEBUG ashpd::helpers] Received request path /org/freedesktop/portal/desktop/request/1_204/ashpd_yhJG5wl3k7
[2022-03-02T09:45:02Z INFO  ashpd::helpers] Received signal 'Response' on 'org.freedesktop.portal.Request'
[2022-03-02T09:45:02Z DEBUG ashpd::helpers] Message body: '"\u{0}\u{0}\u{0}\u{0}`\u{0}\u{0}\u{0}\u{7}\u{0}\u{0}\u{0}streams\u{0}\ta(ua{sv})\u{0}\u{0}@\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}�\u{0}\u{0}\u{0}8\u{0}\u{0}\u{0}\u{8}\u{0}\u{0}\u{0}position\u{0}\u{4}(ii)\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{4}\u{0}\u{0}\u{0}size\u{0}\u{4}(ii)\u{0}\u{0}\u{0}\n\u{0}\u{0}�\u{5}\u{0}\u{0}"'
Error: Zbus(Variant(Message("missing field `streams`")))
```

**Comment by bilelmoussaoui** [comment]
That makes me believe the issue is somewhere in xdg-desktop-portal-wtr but let us debug this a bit more, do you mind using https://flathub.org/apps/details/org.freedesktop.Bustle, start a session bus recording, run your script and save the generated graph as pcap file so I can re-open it locally and see what is exactly being sent through the bus

**Comment by bilelmoussaoui** [comment]
It seems to properly contain everything needed `(uint32 0, {'streams': <[(uint32 140, {'position': <(0, 0)>, 'size': <(2560, 1440)>})]>})`

**Comment by bilelmoussaoui** [comment]
Could you replace the `                message.body::<Response<zvariant::OwnedValue>>()` to `message.body::<Response<HashMap<Vec<u8>, zvariant::OwnedValue>>>`

**Comment by ModProg** [comment]
`Error: Zbus(Variant(Message("invalid type: character `s`, expected `v`, `a` or `(`")))`

**Comment by bilelmoussaoui** [comment]
Could you try the screenshot portal (which is supported by wlr portals) and see if it fails similarly as well?

**Comment by bilelmoussaoui** [comment]
My guess is then something is wrong in https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/screencast/screencast.c#L448-L452 

In order to confirm that, could you paste the body as bytes without converting it to a string?

**Comment by ModProg** [comment]
The error seams to be in `StreamProperties`, because I created a `StreamProperties2` without any content and was able to parse this:
```
[ashpd/src/desktop/screencast.rs:437] streams = Streams2 {
    streams: [
        Stream2(
            140,
            StreamProperties2,
        ),
    ],
    restore_token: None,
}
```

**Comment by ModProg** [comment]
I guess it is the missing `source_type`:
```
[ashpd/src/desktop/screencast.rs:440] streams = Streams2 {
    streams: [
        Stream2(
            140,
            StreamProperties2 {
                id: None,
                position: Some(
                    (
                        0,
                        0,
                    ),
                ),
                size: Some(
                    (
                        2560,
                        1440,
                    ),
                ),
            },
        ),
    ],
    restore_token: None,
}
```

**Comment by bilelmoussaoui** [comment]
Oh that is interesting. The first error was very confusing, that could indeed be the issue

**Comment by bilelmoussaoui** [comment]
Indeed, seems like the property was added on the v3 of the dbus interface which is probably not supported by the wlr implementation yet. I don't know why I didn't make it optional since the start... anyway, thanks for debugging! I will do a new release soon-ish with the fix once it lands. 

Will update the demo as well

**Comment by bilelmoussaoui** [comment]
0.2.5 is out with the fix

**Comment by ModProg** [comment]
I tested the demo. :+1:
