### ISSUE TITLE
Convenient and dependency-minimal WindowIdentifier creation

### ISSUE THREAD

**Issue by jneem** [bilelmoussaoui/ashpd#52]
If I have an XID or a wayland surface, I can convert it to `WindowIdentifier` using `from_raw_handle`. But, it requires the "raw_handle" feature (including potentially unnecessary dependencies) and a side-trip through `RawWindowHandle`. It would be nice to have a more direct path.

#51 has a quick fix for x11, but a wayland version would be nice too (and maybe there's a better way to organize them? #51 was literally just the first thing that I thought of)

**Comment by bilelmoussaoui** [comment]
For Wayland, we would need the wayland-rs dependencies. Although I agree the current code is a bit of a mess and I plan to clean that up and split things to smaller modules that are easier to read and maintain as well.

I will let you know once my changes are ready

**Comment by bilelmoussaoui** [comment]
From druid perspective, what is the type you have access to in a Wayland use case ?

**Comment by jneem** [comment]
I'm not super familiar with that code, but it appears to be a `wayland_client::Main<wayland_client::protocol::wl_surface::WlSurface>`.

**Comment by bilelmoussaoui** [comment]
Awesome, thanks!
