### ISSUE TITLE
Can't create a FileFilter with no name

### ISSUE THREAD

**Issue by melix99** [bilelmoussaoui/ashpd#58]
Creating a FileFilter with an empty name (`FileFilter::new("")`) makes the OpenFile portal to error out. I think it is generally possible to create an unnamed filter, or at least this seems possible with GtkFileChooserNative, so I guess this is a bug.

**Comment by bilelmoussaoui** [comment]
That doesn't seem to be the case per https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-FileChooser.OpenFile or any of the FileChooser methods. Quoting the docs

> filters a(sa(us))
>   List of serialized file filters.
>    Each item in the array specifies a single filter to offer to the user. The first string is a user-visible name for the filter. The a(us) specifies a list of filter strings, which can be either a glob-style pattern (indicated by 0) or a mimetype (indicated by 1). Patterns are case-sensitive. To match different capitalizations of, e.g. '*.ico', use a pattern like '*.[iI][cC][oO]'.
>    Example: [('Images', [(0, '*.ico'), (1, 'image/png')]), ('Text', [(0, '*.txt')])]
>    Note that filters are purely there to aid the user in making a useful selection. The portal may still allow the user to select files that don't match any filter criteria, and applications must be prepared to handle that.

**Comment by bilelmoussaoui** [comment]
I will have a look at gtk to see what it does here.

**Comment by bilelmoussaoui** [comment]
That is what the gtk implementation calls, https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkfilefilter.c#L965 so it seems to always include the filter name

**Comment by bilelmoussaoui** [comment]
I would assume the issue comes from the portal itself, please reopen if the portals (xdg-desktop-portal) made it clear the filter name could be an empty string.
