### ISSUE TITLE
Add more Portals to demo

### ISSUE THREAD

**Issue by JakobDev** [bilelmoussaoui/ashpd#63]
The Demo does currently not support all Portals. Would be nice, if you could add the missing Portals to the Demo.

**Comment by bilelmoussaoui** [comment]
Which portals you are thinking of?

**Comment by JakobDev** [comment]
Just all Portals that are suitable for the Demo. The Demo is a nice Way to explore the Portal interactivity and see how the behave. For me as a developer it is a better Way to see if the Portals fit my needs than just reading the Documentation.

**Comment by bilelmoussaoui** [comment]
Well, it already has all possible portals. Except the UpdateMonitor thing and some missing options here and there. The remaining ones are not really portals per see and are not available for sandboxed applications.

Please re-open if you have specific things in mind that I might have missed.

**Comment by JakobDev** [comment]
Examples for missing Portals would be Gamemode, Trash, Secrets, Settings and the new Dynamic Launcher Portal.

**Comment by bilelmoussaoui** [comment]
Secrets is available, it is just hidden. Trash/GameMode, I have no idea how to present them.  Dynamic launcher portal doesn't have an available implementation that I could test on my machine ,the only available implementation is GNOME 43 material. 

Regarding the Settings one, it is fairly weird portal, maybe we could display the color-scheme key, and tbh it is not worth an issue, if someone wants to send a PR feel free to do so.

**Comment by JakobDev** [comment]
KDE has added supported for the Dynamic Launcher Portal in 5.25, so you can test it now.
