### ISSUE TITLE
desktop::background: Example does not work

### ISSUE THREAD

**Issue by sophie-h** [bilelmoussaoui/ashpd#8]
The output looks fine

```
true
true
```

but nothing happens, nothing in the logs. I am currently running this outside of flatpak. I also tried `logger test` to get a syslog entry, but also doesn't work.

```
$ flatpak --version
Flatpak 1.10.1
```

**Comment by bilelmoussaoui** [comment]
Aha, It's one of the portals that I couldn't properly test.

**Comment by sophie-h** [comment]
Everything fine with ashpd here. The feature only works inside of flatpaks. The user decision is permanently stored an can be reset with `flatpak permission-remove background background `.

The portal should probably return an error if the feature is not supported outside of flatpak. But that's not ashpd's fault.

**Comment by bilelmoussaoui** [comment]
Thanks for the head up! happy that i have nothing to fix yet.

**Comment by bilelmoussaoui** [comment]
Actually, I will reopen this to add a note on the docs about this
