### ISSUE TITLE
Examples don't work properly

### ISSUE THREAD

**Issue by orowith2os** [bilelmoussaoui/ashpd#94]
Hi, I'm currently trying to use ashpd to get a PipeWire video stream to extract the mouse metadata (position, specifically).

However, when I try the examples given in the README, it fails on the `use ashpd::` portion:

``` --> src/main.rs:1:5
  |
1 | use ashpd::desktop::screenshot::ColorResponse;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ColorResponse` in `desktop::screenshot`
  ```
  Is there some other way I'm supposed to use this?

**Comment by bilelmoussaoui** [comment]
the examples are using the git version of the code, check the v0.3 branch.
